name: vine
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip:
      - clip @ git+https://github.com/openai/CLIP.git
      - einops==0.8.0
      - numpy==1.26.4
      - open-clip-torch==2.26.1
      - opencv-python==4.6.0.66
      - pillow==10.4.0
      - scipy==1.11.1
      - timm>=0.9.2
      - tokenizers
      - torch==2.0.1
      - torchdata==0.6.1
      - torchmetrics==0.2.0
      - torchvision==0.15.2
      - tqdm>=4.65.0
      - triton==2.0.0
      - urllib3==1.26.19
      - xformers==0.0.20
      - streamlit-keyup==0.2.0
      - lpips
      - clean-fid
      - peft==0.11.1
      - dominate
      - gradio==3.43.1
      - transformers==4.43.3
      - tokenizers==0.19.1
      - accelerate==0.30.0
      - datasets==2.20.0
      - pilgram
      - kornia
      - wandb
      - scikit-image
      - scikit-learn
      - ipykernel
      - sentencepiece
      - easydict